<a href="https://colab.research.google.com/github/NesanK96/Data-Science/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print("Null Vector with Integer elements:", np.zeros(10, dtype=int))

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np

# x = np.zeros(10)

# print(x.size)
# print(x.itemsize)

A = np.array([10, 25.0, -100])
print("Array 'A':")
print("Size of the array: ", A.size)
print("Memory of one array element: ", A.itemsize)

print("Total memory consumed by the array: ", A.size*A.itemsize)

print("Total memory consumed by the array using 'nbytes' method: ", A.nbytes)

# A.size*A.itemsize == A.nbytes

B = np.array([[10, 25.05, -100], [-3467, -6669, 10.2756]])
print('\nArray \'B\': ')
print("Size of the array: ", B.size)
print("Memory of one array element: ", B.itemsize)

print("Total memory consumed by the array: ", B.size*B.itemsize)

Array 'A':
Size of the array:  3
Memory of one array element:  8
Total memory consumed by the array:  24
Total memory consumed by the array using 'nbytes' method:  24

Array 'B': 
Size of the array:  6
Memory of one array element:  8
Total memory consumed by the array:  48


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [30]:
%run python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np

x = np.zeros(10)

print("Null vector of size '10': ",x)

x[4] = 1

print("After x[4] = 1, the vector becomes: ", x)

Null vector of size '10':  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After x[4] = 1, the vector becomes:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np

v = np.arange(10)
print(v)

v = np.arange(10,50)
print("\nResult:\n",v)

[0 1 2 3 4 5 6 7 8 9]

Result:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10)

print("Array:", x)

x = x[::-1]

print("\nReversed Array:", x)

Array: [0 1 2 3 4 5 6 7 8 9]

Reversed Array: [9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(9)

print(x)

z = x.reshape(3,3) # z = np.arange(9).reshape(3,3)

print("\n3x3 Matrix:\n",z)

[0 1 2 3 4 5 6 7 8]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# B = np.array([[10, 25.05, -100], [-3467, -6669, 10.2756]])

# print(B)

# b = np.array([10, 25.05, -100, 3467, -6669, 10.2756]).reshape(2,3)

# print("\n",b)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.array([1,2,0,0,4,0])

np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x = np.eye(3, 3) # (N,M-optional, dtype - optional)

print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.eye(3, dtype = int) # (N,M-optional, dtype - optional) - N -rows, M -columns(optional)

print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random(3,3,3)

In [ ]:
x = np.random.random((3,3,3))

# evertime the value assigned randomly

print(x)

[[[0.05165727 0.87196552 0.8038275 ]
  [0.88914811 0.91589797 0.49244595]
  [0.90700371 0.28657509 0.95412943]]

 [[0.4306916  0.56164843 0.92243825]
  [0.30655954 0.19760329 0.55186246]
  [0.83701223 0.89399098 0.93242637]]

 [[0.7573045  0.80889706 0.86564827]
  [0.0888287  0.79185047 0.90196651]
  [0.14767948 0.21452633 0.28468323]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
z = np.random.random((10,10,10))

# print(z)

print("min:", z.min())
print('max:', z.max())

min: 0.0019158789508614271
max: 0.9992880967026289


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
z = np.random.random(30)

print("z:\n",z)

print("\nz mean:",z.mean())

z:
 [0.02555271 0.56272714 0.17376545 0.2463388  0.94725899 0.55051179
 0.94056504 0.86805157 0.25821676 0.51552506 0.4024415  0.69957453
 0.27951099 0.48779472 0.07084657 0.99640819 0.15293383 0.11462942
 0.85880764 0.59583737 0.8555238  0.63578407 0.60094106 0.55836181
 0.67912379 0.70667099 0.06846539 0.46683168 0.64487444 0.58259616]

z mean: 0.5182157093996665


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5), dtype=int)  # ones(shape = (x,y) or x, dtype - optional)

print("Original:\n", x)

Original:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
x[1:-1,1:-1] = 0               # x[row,column]
print("Output:", "\n", x)

Output: 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
# Original

x = np.arange(1,10).reshape(3,3)

y = np.arange(1,10)

print(x)
print("\n",y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 2 3 4 5 6 7 8 9]


In [ ]:
# pad(array, pad_width, mode, [constant_values (default:0)] when mode 'constant]

z = np.pad(x, pad_width=1, mode='constant') # modes - constant, edge, maximum, minimum, mean, median

Z = np.pad(y, pad_width=5, mode='constant')

print("x pad:\n", z)

print("\ny pad:", Z)


x pad:
 [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]

y pad: [0 0 0 0 0 1 2 3 4 5 6 7 8 9 0 0 0 0 0]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)

nan


In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
print(np.nan - np.nan)

nan


In [ ]:
print(3*0.1,"\n") # to check, why false?

0.3 == 3 * 0.1 

0.30000000000000004 



False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a = np.arange(1,6)

print("Main Diagonal:\n",np.diag(a))

# a = np.diag([1,2,3,4,5])
# print(a)

Main Diagonal:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
# x = np.zeros((8,8), dtype = int)

x = np.ones((8,8), dtype = int)

print(x)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
# x[::2, 1::2] = 0  # x[row, column] ----> when np.zeros used
# x[1::2, ::2] = 0

x[::2, ::2] = 0     # x[row, column]
x[1::2, 1::2] = 0
print("Check board pattern:\n",x)

Check board pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
# a = np.arange(6*7*8).reshape(6,7,8)
# print(a)
# print("unravel_index:\n",np.unravel_index(99, a))

print("unravel_index:\n",np.unravel_index(99, (6,7,8)))

unravel_index:
 (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a = np.arange(2)
b = a[::-1]

print(np.tile((a, b), (4,4))) # np.tile(array, repetitions)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5,5))

print("Original matrix:\ta:\n\n",a)

Min = a.min()
Max = a.max()

a = (a-Min)/(Max-Min)
print("\nNormalized matrix:\ta=(a-min)/(max-min)\n\n", a)

Original matrix:	a:

 [[0.84397367 0.21449694 0.42234749 0.30674621 0.39510879]
 [0.58780185 0.97302446 0.93863168 0.11867336 0.22091595]
 [0.83296616 0.03718005 0.7492118  0.97858166 0.7239764 ]
 [0.82938294 0.24573326 0.54948441 0.2267955  0.31325518]
 [0.02073392 0.65261676 0.84924573 0.2709308  0.81854939]]

Normalized matrix:	a=(a-min)/(max-min)

 [[0.85946828 0.20229    0.41928748 0.29859891 0.39085009]
 [0.59202304 0.99419825 0.95829193 0.10224949 0.2089915 ]
 [0.84797636 0.01716988 0.76053619 1.         0.73419026]
 [0.84423545 0.23490095 0.55201935 0.21512979 0.30539433]
 [0.         0.65969028 0.86497235 0.26120737 0.83292515]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a = np.arange(5*3).reshape(5,3)
b = np.arange(3*2).reshape(3,2)

x = np.dot(a,b)

print("a:\n",a)
print("b:\n",b)
print("x:\n",x)

a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
b:
 [[0 1]
 [2 3]
 [4 5]]
x:
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [ ]:
a = np.arange(5*3).reshape(5,3)
b = np.arange(3*2).reshape(3,2)

z = a@b #alternate - @ for np.dot()

print("a:\n",a)
print("b:\n",b)
print("x:\n",x)

a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
b:
 [[0 1]
 [2 3]
 [4 5]]
x:
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
z = np.arange(1,12)

z[(4<z) & (z<9)] *= -1 #between z[3]:z[8]

print("'0' based indexing:\n")
print(z)



# y = np.arange(1,12)
# y[4:8:] *= -1
# print(y)

'0' based indexing:

[ 1  2  3  4 -5 -6 -7 -8  9 10 11]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
import numpy as np

a = np.array([10.02, 21.12, 73, 4, 6])

print(np.sum(a))

114.14


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# print(range(5))
# print(sum(range(5))) # sum(0,1,2,3,4)
# print(sum(range(5),-1)) # sum(0,1,2,3,4),-1

# print(sum(range(1,5),-3))

# from numpy import *
# print(sum(range(5),-1))

range(0, 5)
10
9
7
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(1,6)

print(z)

[1 2 3 4 5]


In [ ]:
print(z**z)

# [1 2*2 3*3*3 4*4*4*4 5*5*5*5*5]

[   1    4   27  256 3125]


In [ ]:
# print(1 << z >> 1)  # --- > o/p: [ 1  2  4  8 16]

# print(1 << z << 2)  # --- > o/p: [  8  16  32  64 128]

# print(2 << z << 1)  # --- > o/p: [  8  16  32  64 128]

# print(2 << z << 2)  # --- > o/p: [ 16  32  64 128 256]

# print(1 << z << 3)  # --- > o/p: [ 16  32  64 128 256]

# print(3 << z << 1)  # --- > o/p: [ 12  24  48  96 192]

# print(2 << z << 3)  # --- > o/p: [ 32  64 128 256 512]

# print(3 << z << 2)  # --- > o/p: [ 24  48  96 192 384]

# print(3 << z << 3)  # --- > o/p: [ 48  96 192 384 768]


In [ ]:
print(2<<z<<z)

[   8   32  128  512 2048]


In [ ]:
print(z <- z)

[False False False False False]


In [ ]:
print(1j*z)

[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]


In [ ]:
print(z/1/1)

[1. 2. 3. 4. 5.]


In [ ]:
print(z<z>z)

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))

# Zero division not possible

nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(np.array(1) / np.array(5))

0.2


In [ ]:
print(np.array(0) // np.array(0))

0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print(np.array(10) // np.array(5))

2


In [ ]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print(x)

print("\n",np.abs(x))

# print("\n", np.ceil(np.abs(x), x))

print("\n",np.copysign(np.ceil(np.abs(x)), x))

[-0.16389531  6.66700166 -1.72768661  1.25342772 -3.04071409  6.90870473
  0.46805593 -1.76614128 -7.41433399  9.98312295]

 [0.16389531 6.66700166 1.72768661 1.25342772 3.04071409 6.90870473
 0.46805593 1.76614128 7.41433399 9.98312295]

 [-1.  7. -2.  2. -4.  7.  1. -2. -8. 10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.arange(1,26).reshape(5,5)
x2 = np.arange(15,40).reshape(5,5)

In [ ]:
print("\n", x1)
print("\n", x2)


 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [ ]:
print(np.intersect1d(x1,x2))

[15 16 17 18 19 20 21 22 23 24 25]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np
x = np.seterr(all = 'ignore')
z = np.ones(1)/0

In [ ]:
# with np.errstate(divide = 'warn'): 
#   z = np.ones(1)/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [ ]:
with np.errstate(divide = 'ignore'):
  z = np.ones(1)/0

# all: Literal['ignore', 'warn', 'raise', 'call', 'print', 'log']

# divide: Literal['ignore', 'warn', 'raise', 'call', 'print', 'log']

# over:

# under:

# invalid

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D') # (number of units, date/time)

tomorrow = today + np.timedelta64(1, 'D')

# timedelta64 data type was created to complement datetime64. 
# The arguments for timedelta64 are a number:
#           to represent the number of units (eg: 2) and a date/time unit (eg: Y), 
#                     such as (D)ay, (M)onth, (Y)ear, (h)ours, (m)inutes, or (s)econds.

last_year_same_Date = today - np.timedelta64(1, 'm')

print("Today:", today)
print("\nYesterday:", yesterday)
print("\nTomorrow:", tomorrow)

print("\nLast_year_same_Date:", last_year_same_Date)

Today: 2022-04-09

Yesterday: 2022-04-08

Tomorrow: 2022-04-10

Last_year_same_Date: 2022-04-08T23:59


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
july = np.arange ('2016-07', '2016-08', dtype = 'datetime64[D]')

print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(5)     # 1,1,1,1,1

B = np.ones(5)*2   # 2,2,2,2,2

np.add(A, B, out=B) # (A+B) = B

array([3., 3., 3., 3., 3.])

In [ ]:
A, B

(array([1., 1., 1., 1., 1.]), array([3., 3., 3., 3., 3.]))

In [ ]:
np.negative(A,out=A)  # A = -A

array([-1., -1., -1., -1., -1.])

In [ ]:
# np.divide(B, 2, out = B)  # [2., 2., 2., 2., 2.]

np.divide(A, 2, out = A)  # (A/2)

array([-0.5, -0.5, -0.5, -0.5, -0.5])

In [ ]:
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
z = np.random.uniform(2, 5, 10)

print(z)

[4.84920147 2.21802219 4.53463158 3.27168352 3.61606969 4.31989865
 2.65052065 2.33939555 4.55568349 3.54468994]


In [ ]:
print(z%2)

[0.84920147 0.21802219 0.53463158 1.27168352 1.61606969 0.31989865
 0.65052065 0.33939555 0.55568349 1.54468994]


In [ ]:
print(np.floor(z))

[4. 2. 4. 3. 3. 4. 2. 2. 4. 3.]


In [ ]:
print(np.ceil(z))

[5. 3. 5. 4. 4. 5. 3. 3. 5. 4.]


In [ ]:
print(z.astype(int))

[4 2 4 3 3 4 2 2 4 3]


In [ ]:
print(np.trunc(z))

[4. 2. 4. 3. 3. 4. 2. 2. 4. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a = np.zeros((5,5), dtype = int)

a += np.arange(5)

print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
a = np.arange(5)

z = np.tile((a), (5,1))
print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
# numpy.fromiter(iter, dtype, count=- 1, *, like=None)

def gen():
  for x in range(1,10):
    x = x**2
    yield (x)

a = np.fromiter(gen(), dtype=int)

print(a)

[ 1  4  9 16 25 36 49 64 81]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

a = np.linspace(0,1, num=11, endpoint=False) # to assign last element to value below, a[last] != 1.

a = a[1::] # to leave a[0] = 0. 

print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a = np.random.randint(-2, 5, 10)

a.sort()

print(a)

[-2 -2 -2 -1  0  1  1  2  3  4]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a = np.random.randint(2, 5, 10)
print(a)
np.add.reduce(a) # np.sum(a)

[3 2 4 3 3 2 3 3 4 3]


30

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(1,3,5)
b = np.random.randint(1,3,5)

print(a,b)

[2 2 2 2 2] [2 1 1 1 2]


In [ ]:
if np.allclose(a,b):
  print(True)
else:
  print(0)

0


In [ ]:
if np.array_equal(a,b):
  print(1)
else:
  print(False)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z = np.arange(1,6)

print(z)

z[0] = 10
z[2:] =0

print("\n",z)

[1 2 3 4 5]

 [10  2  0  0  0]


In [ ]:
z = np.arange(1,6)

z.flags.writeable = False

z[0] = 10
z[2:] = 0

print(z)

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [33]:
cartesian = np.random.randint(1,5,20).reshape(10,2)

# Cartesian coordinate system uses the (real) number line as the reference

# r = sqrt(x**2+y**2) ---> reshape

# x = rcos(theta), y = rsin(theta)

# Polar coordinates use an angle and a length as the coordinates

x,y = cartesian[:,0], cartesian[:,1]

r = np.sqrt(x**2+y**2)

p = np.arctan2(y,x)

print(r)
print(p)

[3.60555128 4.12310563 2.23606798 2.82842712 4.12310563 2.23606798
 5.         2.23606798 4.12310563 4.47213595]
[0.98279372 1.32581766 1.10714872 0.78539816 1.32581766 0.46364761
 0.64350111 0.46364761 1.32581766 0.46364761]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
z = np.random.randint(3,10,10)

print(z)

a = np.argmax(z)

z[a] = 0

print("\nResult:\n",z)

[3 7 6 4 8 8 6 7 8 7]

Result:
 [3 7 6 4 0 8 6 7 8 7]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [34]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [38]:
x = np.arange(8)
y = x + 0.5
z = 1.0 / np.subtract.outer(x, y)

print(np.linalg.det(z))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [39]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import sys

np.set_printoptions(threshold = sys.maxsize)

z = np.random.random((5,5,5))

print(z)

[[[0.41909736 0.42854665 0.68007786 0.52082445 0.18720802]
  [0.36117382 0.71089663 0.56603691 0.147935   0.5902505 ]
  [0.60432519 0.61010286 0.27572895 0.76018788 0.08563519]
  [0.5830286  0.33546199 0.17973139 0.51313267 0.61900338]
  [0.112784   0.00671846 0.40229832 0.28692992 0.52877202]]

 [[0.89256166 0.08762229 0.12618744 0.68088371 0.37438317]
  [0.16952327 0.86692614 0.32381616 0.19706581 0.69582718]
  [0.15616453 0.81277367 0.7863924  0.45002403 0.86518364]
  [0.50969573 0.14229217 0.59982243 0.3579076  0.80627457]
  [0.52036352 0.72468962 0.8342166  0.14190214 0.0032595 ]]

 [[0.45546402 0.51154615 0.23821378 0.66671293 0.41869458]
  [0.70931118 0.46586244 0.65361727 0.85881721 0.82372845]
  [0.27526202 0.56080291 0.84747553 0.50632246 0.36073694]
  [0.73245196 0.35459171 0.03418121 0.61298081 0.51455601]
  [0.31287267 0.72492002 0.32389494 0.68580218 0.43258243]]

 [[0.62557023 0.96247163 0.4566274  0.00387509 0.28506707]
  [0.09682024 0.32847194 0.14985564 0.37719689 0.8

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
z = np.arange(50)
a = np.random.uniform(0,100)

print(z)

print("\n",a)

x = (np.abs(z-a)).argmin()
print("\nClosest Value:",z[x])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

 34.3367748305276

Closest Value: 34


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                   ('y', float)]),
                    ('color',    [ ('r', float),
                                   ('g', float),
                                   ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [4]:
x = np.random.random((10,2))
y,z = np.atleast_2d(x[:,0], x[:,1])
a = np.sqrt( (y-y.T)**2 + (z-z.T)**2)
print(a)

[[0.         0.47063958 0.70560761 0.24150072 0.23957298 0.61938436
  0.72194291 0.63126628 0.50002254 0.63966565]
 [0.47063958 0.         0.30234035 0.24889515 0.28275753 0.20555117
  0.33870427 0.3225228  0.39607111 0.17606546]
 [0.70560761 0.30234035 0.         0.46443701 0.57017622 0.3971719
  0.50563208 0.55572154 0.36192685 0.1749685 ]
 [0.24150072 0.24889515 0.46443701 0.         0.18279701 0.43284143
  0.55558996 0.49617227 0.31994091 0.40578006]
 [0.23957298 0.28275753 0.57017622 0.18279701 0.         0.38968124
  0.48409285 0.39185194 0.50000442 0.45849086]
 [0.61938436 0.20555117 0.3971719  0.43284143 0.38968124 0.
  0.13378609 0.15970314 0.59485078 0.22220423]
 [0.72194291 0.33870427 0.50563208 0.55558996 0.48409285 0.13378609
  0.         0.12467222 0.72825237 0.33462013]
 [0.63126628 0.3225228  0.55572154 0.49617227 0.39185194 0.15970314
  0.12467222 0.         0.71754366 0.38099001]
 [0.50002254 0.39607111 0.36192685 0.31994091 0.50000442 0.59485078
  0.72825237 0.717543

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
z = np.arange(1,5, dtype = np.float32)
print(z)

z = z.astype(np.int32, copy = False)
print(z)


[1. 2. 3. 4.]
[1 2 3 4]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

String = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
x = np.genfromtxt(String, delimiter=",", dtype=int)
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.arange(3*3).reshape(3,3)
for x, y in np.ndenumerate(Z):
    print(x, y)
print("\n************")
for index in np.ndindex(Z.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

************
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [3]:
import numpy as np

x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))

z = np.sqrt(x*x+y*y)

sigma, mu = 1.0, 0.0

a = np.exp(-( (z-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(a)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5
p = 10
z = np.ones((n,n), dtype =int)
np.put(z, np.random.choice(range(n*n), p),0)
print (z)

[[0 1 1 0 1]
 [1 0 1 1 1]
 [0 1 1 1 1]
 [1 0 0 1 1]
 [1 0 1 1 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.random((3,5))

print(x, "Mean:", x.mean())

y = x.mean(axis = 1, keepdims = True)

z = x-y
print("\n",z)

[[0.7749399  0.25026345 0.03630364 0.9297054  0.35074205]
 [0.27254105 0.83654404 0.27411092 0.42373142 0.10729797]
 [0.61012494 0.06834878 0.72791891 0.10995189 0.80576662]] Mean: 0.43855273186550625

 [[ 0.30654901 -0.21812744 -0.43208725  0.46131451 -0.11764884]
 [-0.11030403  0.45369896 -0.10873416  0.04088634 -0.27554711]
 [ 0.14570271 -0.39607345  0.26349668 -0.35447033  0.34134439]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
z = np.random.randint(1,5,(3,3))

print(z)

# print(np.argsort(z))

print("\n",z[z[:,1].argsort()])

[[1 3 1]
 [2 3 2]
 [2 2 1]]

 [[2 2 1]
 [1 3 1]
 [2 3 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(1,5,5)
print(x)

y = 2.75

z = x.flat[np.abs(x - y).argmin()]
print("\n",z)

[1.15614603 3.88366203 4.03285836 1.59915514 1.55411184]

 3.883662031710553


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
import numpy as np

x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)

print(x)
print("\n",y)
# numpy.nditer(op,  op_axes=None, itershape=None,)

z = np.nditer([x,y, None])

for a,b,c in z: 
  c[...] = a+b

print("\n",z.operands[2])


[[0 1 2]]

 [[0]
 [1]
 [2]]

 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [6]:
x = np.ones(10)
z = np.random.randint(0,len(x),20)
x += np.bincount(z, minlength=len(x))
print(x)

[3. 1. 6. 2. 2. 4. 3. 2. 3. 4.]


In [7]:
np.add.at(x,z,1)
print(z)

[5 4 2 3 5 2 0 6 9 9 9 2 8 2 8 6 5 0 2 7]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = np.arange(1,6)
y = np.random.randint(1,9,5)

print(x)
print("\n",y)

f = np.bincount(y,x)
print("\n",f)

[1 2 3 4 5]

 [5 6 1 7 7]

 [0. 3. 0. 0. 0. 1. 2. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [14]:
w,h = 16,16

x = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

y = x[...,0]*256*256 + x[...,1]*256 +x[...,2]

n = len(np.unique(y))

print(np.unique(x))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [13]:
x = np.random.randint(0,10,(3,4,3,4))

sum = x.sum(axis=(-2,-1))
print(sum)

sum = x.reshape(x.shape[:-2] + (-1,)).sum(axis=-1)
print("\n",sum)

[[58 58 53 54]
 [61 37 52 44]
 [71 64 51 52]]

 [[58 58 53 54]
 [61 37 52 44]
 [71 64 51 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [15]:
x = np.random.uniform(0,1,100)
y = np.random.randint(0,10,100)

sum = np.bincount(y, weights=x)
count = np.bincount(y)
mean = sum / count

print(mean)

[0.51879313 0.42443665 0.60957788 0.4741182  0.40319023 0.58064906
 0.59151184 0.41868541 0.66154764 0.4753749 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

b = a[::-1]
print('\n',b)

m = a@b # or np.dot(a,b)
print('\n',m)

x = np.diag(m)
print('\nOuput:',x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[7 8 9]
 [4 5 6]
 [1 2 3]]

 [[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]

Ouput: [ 18  69 138]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
import numpy as np

x = np.array([1,2,3,4,5])
y = 3
z = np.zeros(len(x) + (len(x)-1)*(y))

#---> [1,0,0,0,2,0,0,0,....5] ---> length = 1-0's-5 = 12 + elements 5 = 17

z[::y+1] = x

print(z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
# print(a)
b = 2*np.ones((5,5))
# print(b)
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(25).reshape(5,5)

x[[0,2]] = x[[2,0]]

print(x)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [16]:
a = np.random.randint(0,100,(10,3))

x = np.roll(a.repeat(2,axis=1),-1,axis=1)
x = x.reshape(len(x)*3,2)
x = np.sort(x,axis=1)

y = x.view( dtype=[('p0',x.dtype),('p1',x.dtype)] )
y = np.unique(y)
print(y)

[( 0, 53) ( 0, 72) ( 7, 65) ( 7, 67) ( 9, 22) ( 9, 91) (19, 60) (19, 83)
 (22, 91) (23, 75) (23, 84) (28, 95) (37, 50) (37, 59) (38, 67) (38, 69)
 (39, 64) (39, 65) (46, 76) (46, 94) (50, 59) (53, 72) (60, 83) (64, 65)
 (65, 67) (67, 69) (75, 84) (76, 94) (95, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [17]:
a = np.bincount([1,1,2,3,4,4,6])
b = np.repeat(np.arange(len(a)), a)
print(b)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [18]:
def x(a, n=3) :
    y = np.cumsum(a, dtype=float)
    y[n:] = y[n:] - y[:-n]
    return y[n - 1:] / n
z = np.arange(20)

print(x(z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [21]:
z = np.random.randint(0,2,100)
print(np.logical_not(z, out=z))

Z = np.random.uniform(-1.0,1.0,100)
print('\n\n',np.negative(z, out=z))

[0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0
 1 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0
 0 1 0 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 1 0]


 [ 0  0  0 -1 -1  0  0  0 -1 -1  0  0  0  0 -1 -1  0  0 -1 -1 -1 -1 -1 -1
  0  0 -1  0 -1  0  0  0 -1  0 -1 -1  0 -1 -1 -1 -1 -1  0 -1 -1  0 -1  0
  0  0 -1  0  0 -1  0 -1 -1 -1 -1  0 -1 -1  0 -1  0 -1 -1 -1 -1 -1  0 -1
 -1  0  0 -1  0 -1  0 -1 -1  0 -1 -1  0  0  0 -1 -1 -1 -1  0 -1  0 -1 -1
  0  0 -1  0]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)

R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
x = np.random.uniform(0,1,(5,5))

a,b,c = np.linalg.svd(x)

rank = np.sum(b > 1e-10)

print(rank)

5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.array([1,2,3,1,5,3,2,7,4,9,1])

print(np.bincount(x).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [27]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0]-3)
j = 1 + (z.shape[1]-3)

a = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=z.strides + z.strides)
print(a)

[[[[ 2.37792781e-01  8.82735607e-01 -8.57000549e-01]
   [ 7.90741088e-01  5.39990666e-01  4.66540422e-01]
   [ 1.99027543e-01  2.39590676e-01  3.39460147e-01]]

  [[ 8.82735607e-01 -8.57000549e-01 -5.83005749e-01]
   [ 5.39990666e-01  4.66540422e-01 -6.59415500e-01]
   [ 2.39590676e-01  3.39460147e-01 -6.86661454e-01]]

  [[-8.57000549e-01 -5.83005749e-01 -4.49293274e-01]
   [ 4.66540422e-01 -6.59415500e-01  5.69030244e-01]
   [ 3.39460147e-01 -6.86661454e-01  3.10396091e-01]]

  [[-5.83005749e-01 -4.49293274e-01 -8.44225574e-02]
   [-6.59415500e-01  5.69030244e-01  4.48900530e-01]
   [-6.86661454e-01  3.10396091e-01 -2.63337957e-01]]

  [[-4.49293274e-01 -8.44225574e-02 -2.46795124e-01]
   [ 5.69030244e-01  4.48900530e-01 -7.38971024e-02]
   [ 3.10396091e-01 -2.63337957e-01 -4.64887639e-01]]

  [[-8.44225574e-02 -2.46795124e-01  4.65983141e-01]
   [ 4.48900530e-01 -7.38971024e-02  6.41430315e-01]
   [-2.63337957e-01 -4.64887639e-01  2.88969412e-01]]

  [[-2.46795124e-01  4.65983141e-0

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [28]:
a,b = 10, 20

x = np.ones((a,b,b))
y = np.ones((a,b,1))

z = np.tensordot(x, y, axes=[[0, 2], [0, 1]])
print(z)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [1]:
import numpy as np

x = np.ones((16,16))
y = 4
z = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], y), axis=0),
                                       np.arange(0, x.shape[1], y), axis=1)
print(z)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
x = np.arange(101)
np.random.shuffle(x)
n = 10

print(x[np.argsort(x)[-n::]])

print(x[np.argpartition(-x,n)[::n]])

[ 91  92  93  94  95  96  97  98  99 100]
[99 90 80 47 43 68 46 19  9 16 24]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [3]:
x = np.array([("Hello", 10, 2),
              ("World", 21, 12)])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[(b'Hello', 10.,  2) (b'World', 21., 12)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [13]:
x = np.random.randint(1e2)

print(np.power(x,3))

print(x*x*x)

287496
287496


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [28]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

z = (a[..., np.newaxis, np.newaxis] == b)
out = np.where(z.any((3,1)).all(1))[0]
print(out)

[0 1 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [26]:
x = np.random.randint(0,2,(6,3))
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
Z, z = np.unique(y, return_index=True)

a = x[z]
print(a)

[[0 0 1]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [20]:
a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)

print(np.einsum('i->', a))      
print(np.einsum('i,i->i', a, b))
print(np.einsum('i,i', a, b))    
print(np.einsum('i,j->ij', a, b))

9
[4 2 6 2 2]
16
[[4 4 4 2 4]
 [2 2 2 1 2]
 [6 6 6 3 6]
 [4 4 4 2 4]
 [2 2 2 1 2]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [23]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
a = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
a &= (x.sum(axis=-1) == n)
print(x[a])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [24]:
x = np.random.randn(100) 
n = 1000 
z = np.random.randint(0, x.size, (n, x.size))

m = x[z].mean(axis=1)
a = np.percentile(m, [2.5, 97.5])

print(a)

[-0.17490479  0.15409007]
